### PR TITLE
Pull the jupyter image as part of docker compose file

### PR DESCRIPTION
**Pull request by blueraft**

### CODE REVIEW

**Review by hampusnasstrom — APPROVED** [review]
Awesome, thank you!

**Comment by DanielYang59** [comment]
I believe jupyter image is here for a reason, but wondering if it's possible to make this optional if this is not a core functionality? https://github.com/FAIRmat-NFDI/nomad-distro-template/blob/56d4cd2d78be8663f8b7714bb33d42f3684ac5ae/docker-compose.yaml#L207

In my case it's inflating the total image size and significantly slowing down pulling (on AWS):
```
✔ app Skipped - Image is already being pulled by north               0.0s  
✔ worker Skipped - Image is already being pulled by north            0.0s 
 ✔ proxy Pulled                                                      55.6s  
✔ rabbitmq Pulled                                                    1.3s  
✔ jupyterlab_image Pulled                                            447.5s 
 ✔ north Pulled                                                      208.7s  
✔ elastic Pulled                                                     117.9s  
✔ mongo Pulled                                                       1.1s 
```

**Comment by blueraft** [comment]
This is by design yes. Otherwise, the jupyter image will only be downloaded when a user launches a jupyter container in the NORTH tool (this is very slow and usually lead to a lot of errors and retries). Instead with this PR, we now pull the image upfront, so users who use jupyter containers will have a smoother workflow.

**Comment by DanielYang59** [comment]
Hi Ahmed thanks for the input ;) I guess i would just change the pull policy locally

**Pull request merged**
